# Generated by Django 2.1.1 on 2018-09-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appannonce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='phone',
            field=models.PositiveIntegerField(default='69863425218'),
            preserve_default=False,
        ),
    ]
