# Generated by Django 2.1.1 on 2018-09-24 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appannonce', '0003_auto_20180924_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
