# Generated by Django 2.1.1 on 2018-09-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appannonce', '0004_remove_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='ville',
            field=models.CharField(choices=[('ca', 'casablance'), ('r', 'rabat')], max_length=200),
        ),
        migrations.DeleteModel(
            name='Ville',
        ),
    ]
