# Generated by Django 2.1.1 on 2018-09-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appannonce', '0005_auto_20180924_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='category',
        ),
        migrations.AddField(
            model_name='annonce',
            name='categorie',
            field=models.CharField(choices=[('appartement', 'appartement'), ('vi', 'villa')], default='appartement', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
