# Generated by Django 2.1.1 on 2018-09-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appannonce', '0007_auto_20180924_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='categorie',
            field=models.CharField(choices=[('app', 'appartement'), ('vi', 'villa')], max_length=200),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='typeannonce',
            field=models.CharField(choices=[('lo', 'Location'), ('ve', 'vente')], max_length=10),
        ),
        migrations.AlterField(
            model_name='galerie',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='images/', verbose_name='profile annonce ', width_field='width_field'),
        ),
    ]
