# Generated by Django 2.1.1 on 2018-09-27 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appannonce', '0009_auto_20180925_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galeries', to='appannonce.Galerie'),
        ),
    ]
