# Generated by Django 2.1.1 on 2018-09-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appannonce', '0010_auto_20180927_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galerie',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='settings.MEDIA_ROOT', verbose_name='profile annonce ', width_field='width_field'),
        ),
    ]
