# Generated by Django 2.1.1 on 2018-09-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appannonce', '0011_auto_20180927_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galerie',
            name='image',
            field=models.ImageField(blank=True, default='img/default.png', height_field='height_field', null=True, upload_to='', verbose_name='profile annonce ', width_field='width_field'),
        ),
    ]
